# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54d73e094ef0169b6128550b38f8f8b3fc81fbade2ae64ca68845737222d37567b092c3971192d2fefd02ea65a4aee23ff84481e44620f77687a9dffb777e8c6

test:
  secret_key_base: 3f60c126677fe419628917568ead8b6d5eef7c870c6d7103f14dc4edb5f3db8681c05701ae2f8253a5a1d3a1627ff5863fb6c6b5926d9bc45dcdca37294a30a0

development_server:
  secret_key_base: <%= ENV['BEACON_SECRET_KEY_BASE'] %>

staging:
  secret_key_base: <%= ENV['BEACON_SECRET_KEY_BASE'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['BEACON_SECRET_KEY_BASE'] %>
